### PR TITLE
Adding moving refinement region and moving cooling refinement region

### PR DESCRIPTION
**Pull request by bwoshea**
This PR includes all of the changes for the moving refinement region and the moving cooling refinement region.  It ALSO, as per Molly's request, increases the max number of refinement regions to 8000 so that we are unlikely to run over.  It ALSO ALSO, as per Molly's request, linearly interpolates between outputs.

### CODE REVIEW

**Comment by peeples** [comment]
Crashes if track file starts after current time, as expected.

**Comment by peeples** [comment]
Also crashes if track file does not reach current time, as it should! Huzzah!!

**Comment by peeples** [comment]
The interpolation looks like it is moving the box as expected.

**Comment by peeples** [comment]
In the CoolingRefineRegionLeftEdge / CoolingRefineRegionRightEdge, I have it saying "Default: None". Is this true, or is it [0,0,0]/[1,1,1] ?

**Comment by bwoshea** [comment]
Closing local PR; going to issue one to the main Enzo repository.

**Pull request closed without merging**
